#!/usr/bin/env python3
"""
This script removes the first heading/text from articles that have duplicate titles.
It reads from the duplicate_titles.csv generated by the find_double_title script.

USAGE:
  Dry run (preview changes):
    python3 main.py

  Live mode (actually make changes):
    python3 main.py --live
"""

import sys
from article_first_line_remover import ArticleFirstLineRemover


def main():
    # Check if we're in live mode
    dry_run = True
    if '--live' in sys.argv:
        dry_run = False
        print("\n⚠️  WARNING: Running in LIVE mode - changes will be saved!")
        response = input("Are you sure you want to continue? (yes/no): ")
        if response.lower() not in ['yes', 'y']:
            print("Aborted.")
            return 1
    
    print("🔧 Article First Line Remover")
    print("=" * 60)
    
    try:
        # Initialize the remover
        remover = ArticleFirstLineRemover(
            'CONTENTFUL_SPACE_ID',
            'CONTENTFUL_ENVIRONMENT_ID',
            'CONTENTFUL_MANAGEMENT_TOKEN'
        )
        
        # Read the CSV file
        print("\n=== Reading duplicate titles CSV ===")
        csv_file = '../find_double_title/generated/duplicate_titles.csv'
        pages = remover.read_csv(csv_file)
        
        if not pages:
            print("No pages to process!")
            return 0
        
        # Process all pages
        remover.process_pages(pages, dry_run=dry_run)
        
        if dry_run:
            print("\n💡 This was a dry run. No changes were made.")
            print("   To actually update articles, run: python3 main.py --live\n")
        else:
            print("\n✅ All changes have been saved!\n")
        
        return 0
        
    except Exception as e:
        print(f"\n❌ Error: {str(e)}")
        print("\nPlease check:")
        print("  1. Your .env file has correct credentials")
        print("  2. CONTENTFUL_SPACE_ID is set")
        print("  3. CONTENTFUL_ENVIRONMENT_ID is set")
        print("  4. CONTENTFUL_MANAGEMENT_TOKEN is set")
        print("  5. The duplicate_titles.csv file exists in ../find_double_title/generated/")
        return 1


if __name__ == "__main__":
    exit(main())

